<?php

define('ADDRESS', 'address');
define('AUTHENTICATION_ERROR', 'Kimlik doğrulama hatası oluştu');
define('AVERAGE', 'average');
define('BASE64', 'base64');
define('BIRTHDAY', 'birthday');
define('CITY', 'city');
define('CONTACT', 'contact');
define('COURSE', 'course');
define('COURSE_TYPE', 'course_type');
define('CURRENT_PAGE', 'current_page');
define('CLASS_', 'class');
define('CLASS_ID', 'class_id');
define('CLASS_NAME', 'class_name');
define('CONTENT', 'content');
define('COUNTRY', 'country');
define('CURRENCY', 'currency');
define('DATA', 'data');
define('DAY', 'day');
define('DAY_HOUR_TABLE', 'day_hour_table');
define('DB_USERS_TABLE', 'users');
define('DEMO', 'demo');
define('DISCIPLINE', 'discipline');
define('DISTRICT', 'district');
define('DOMAIN_TURKEY', 'tr');
define('DOT', '.');
define('EMAIL', 'email');
define('EQUAL_SIGN', '=');
define('ERROR', 'error');
define('ETUDE', 'etude');
define('EXPERIENCE', 'experience');
define('EXPRESSION', 'expression');
define('FACILITY', 'facility');
define('FIELDS_VALIDATION_FAILED', 'Alanları doğrulama hatası');
define('FILE_NAME', 'file_name');
define('FILE_TYPE', 'file_type');
define('GROUP', 'group');
define('GROUP_DISCOUNT', 'group_discount');
define('IDENTIFIER', 'id');
define('INDIVIDUAL', 'individual');
define('LANGUAGE', 'language');
define('LECTURE', 'lecture');
define('LECTURES_LIST', 'lectures_list');
define('LECTURE_AREA', 'lecture_area');
define('LECTURE_THEME', 'lecture_theme');
define('LESS_OR_EQUAL_SIGN', '<=');
define('LIKE_SIGN', 'LIKE');
define('LIBRARY', 'library');
define('LIMIT', 'limit');
define('LOCATION', 'location');
define('LOGGED_IN_SUCCESSFULLY', 'Oturum başarıyla açıldı');
define('MAX_PRICE', 'maxPrice');
define('MESSAGE', 'message');
define('NAME', 'name');
define('OVER_INTERNET', 'overInternet');
define('PACKAGE_DISCOUNT', 'packageDiscount');
define('PASSWORD', 'password');
define('PASSWORD_CONFIRMATION', 'password_confirmation');
define('PASSWORD_VALIDATION_FAILED', 'Şifreleri doğrulama hatası');
define('PICTURE', 'picture');
define('PHONE', 'phone');
define('PRICE', 'price');
define('REGISTER_DATE', 'register_date');
define('REGION', 'region');
define('REMEMBER_TOKEN', 'remember_token');
define('SEX', 'sex');
define('STATE', 'state');
define('STAR_SIGN', '*');
define('STATUS', 'status');
define('STATUS_CODE', 'status_code');
define('STUDENT', 'student');
define('STUDENTS', 'students');
define('STUDENT_HOME', 'studentHome');
define('SOMETHING_WRONG_WITH_DB', 'Veri tabanıyla bağlanmada bir sorun oluştu');
define('SUCCESS', 'success');
define('SURNAME', 'surname');
define('THIS_EMAIL_ALREADY_EXIST', 'Bu email zaten mevcut');
define('TOTAL_COUNT', 'total_count');
define('TOTAL_DATA', 'total_data');
define('TOTAL_PAGE', 'total_page');
define('TURKISH_LIRA', 'TRY');
define('TUTOR', 'tutor');
define('TUTOR_HOME', 'tutor_home');
define('TUTOR_ID', 'tutor_id');
define('TYPE', 'type');
define('ONESIGNAL_DEVICE_ID', 'onesignal_device_id');
define('USER', 'user');
define('USER_DOES_NOT_EXIST', 'Böyle bir kullanıcı yok');
define('USER_ID', 'user_id');
define('WELCOME_EMAIL', 'welcome_email');
