<?php

define('ADDRESS', 'address');
define('ANNOUNCEMENT_ID', 'announcement_id');
define('ANNOUNCEMENT_ALREADY_EXIST_WITH_SAME_PARAMETERS', 'Benzer filteler ile bir ilanınız zaten mevcut');
define('ANNOUNCEMENT_CREATED_SUCCESSFULLY', 'İlan başarıyla eklendi');
define('ANNOUNCEMENT_STATUS_ACTIVE', 1);
define('AUTHENTICATION_ERROR', 'Kimlik doğrulama hatası oluştu, lütfen tekrar deneyin');
define('AVAILABLE', 'available');
define('AVERAGE', 'average');
define('AVERAGE_PRICE', 'average_price');
define('AVERAGE_TRY', 'average_try');
define('BASE64', 'base64');
define('BID', 'bid');
define('BIRTHDAY', 'birthday');
define('BOOST', 'boost');
define('CARD_HOLDER_NAME', 'card_holder_name');
define('CARD_NUMBER', 'card_number');
define('CITY', 'city');
define('CITY_ID', 'city_id');
define('CITY_NAME', 'city_name');
define('CHANGES_UPDATED_SUCCESSFULLY', 'Değişiklikler başarıyla güncellendi');
define('CONTACT', 'contact');
define('COURSE', 'course');
define('COURSE_TYPE', 'course_type');
define('COURSE_TYPE_UPDATED_SUCCESSFULLY', 'Ders tipleri başarıyla güncellendi');
define('COUNTRY_CODE', 'country_code');
define('COUNTRY_ID', 'country_id');
define('COUNTRY_NAME', 'country_name');
define('COUNTRY_TURKEY', 'Turkey');
define('COUNTRY_TURKEY_CODE', 'tr');
define('COMMA_SIGN', ',');
define('CREATED_AT', 'created_at');
define('CURRENT_PAGE', 'current_page');
define('CLASS_', 'class');
define('CLASS_ID', 'class_id');
define('CLASS_NAME', 'class_name');
define('CONTENT', 'content');
define('COUNTRY', 'country');
define('CURRENCY', 'currency');
define('CVC', 'cvc');
define('DATA', 'data');
define('DATE', 'date');
define('DATE_FORMAT', 'd/m/Y H:i');
define('DATE_FORMAT_COMPACT', 'dmyHi');
define('DATE_TIME', 'dateTime');
define('DAY_MONTH', 'd/m');
define('DAY', 'day');
define('DAY_HOUR_TABLE', 'day_hour_table');
define('DB_ANNOUNCEMENT_TABLE', 'announcement');
define('DB_AVERAGE_TABLE', 'average');
define('DB_CITY_TABLE', 'city');
define('DB_COUNTRY_TABLE', 'country');
define('DB_FINANCE_TABLE', 'finance');
define('DB_PAID_SERVICE_TABLE', 'paid_service');
define('DB_PROFILE_TABLE', 'profile');
define('DB_LECTURE_TABLE', 'lecture');
define('DB_SUITABLE_COURSE_TYPE_TABLE', 'suitable_course_type');
define('DB_SUITABLE_FACILITY_TABLE', 'suitable_facility');
define('DB_SUITABLE_LOCATION_TABLE', 'suitable_location');
define('DB_SUITABLE_REGION_TABLE', 'suitable_region');
define('DB_STUDENT_TABLE', 'student');
define('DB_TUTOR_LECTURE_TABLE', 'tutor_lecture');
define('DB_OFFER_TABLE', 'offer');
define('DB_USERS_TABLE', 'users');
define('DEMO', 'demo');
define('DESCRIPTION', 'description');
define('DISCIPLINE', 'discipline');
define('DISTRICT', 'district');
define('DISTRICTS', 'districts');
define('DISTRICT_NAME', 'district_name');
define('DOT', '.');
define('EMAIL', 'email');
define('EMAIL_TYPE_PAID_SERVICE', 'email_type_paid_service');
define('EMAIL_TYPE_OFFER_STATUS', 'email_type_offer_status');
define('EMAIL_TYPE_OFFER', 'email_type_offer');
define('EMAIL_TYPE_RESET_PASSWORD', 'email_type_reset_password');
define('EMAIL_TYPE_WELCOME', 'email_type_welcome');
define('EQUAL_SIGN', '=');
define('EQUAL_OR_GREATER_SIGN', '>=');
define('EQUAL_OR_LESS_SIGN', '<=');
define('ERROR', 'error');
define('ETUDE', 'etude');
define('EXPECTATION', 'expectation');
define('EXPERIENCE', 'experience');
define('EXPERIENCE_AVG', 'experience_avg');
define('EXPRESSION', 'expression');
define('EXPIRE_MONTH', 'expire_month');
define('EXPIRE_YEAR', 'expire_year');
define('FACILITY', 'facility');
define('FACILITIES', 'facilities');
define('FACILITIES_UPDATED_SUCCESSFULLY', 'Kolaylıklar başarıyla güncellendi');
define('FIELDS_VALIDATION_FAILED', 'Alanları doğrulama hatası');
define('FILE', 'file');
define('FILE_NAME', 'file_name');
define('FILE_TYPE', 'file_type');
define('FINANCE_ID', 'finance_id');
define('GENDER_DISTRIBUTION', 'gender_distribution');
define('GROUP', 'group');
define('GROUP_DISCOUNT', 'group_discount');
define('HOUR_MINUTE', 'H:i');
define('IDENTIFIER', 'id');
define('IDENTITY_NUMBER', 'identity_number');
define('INDIVIDUAL', 'individual');
define('INVALID_EMAIL_OR_PASSWORD', 'Geçersiz email veya şifre');
define('ITEM', 'item');
define('KEY', 'key');
define('LANGUAGE', 'language');
define('LECTURE', 'lecture');
define('LECTURES', 'lectures');
define('LECTURE_ID', 'lecture_id');
define('LECTURES_LIST', 'lectures_list');
define('LECTURE_AREA', 'lecture_area');
define('LECTURE_DELETED_FROM_LIST_SUCCESSFULLY', 'Ders listeden başarıyla kaldırıldı');
define('LECTURE_THEME', 'lecture_theme');
define('LECTURE_THEMES', 'lecture_themes');
define('LESS_OR_EQUAL_SIGN', '<=');
define('LIKE_SIGN', 'LIKE');
define('LIBRARY', 'library');
define('LIMIT', 'limit');
define('LOCATION', 'location');
define('LOCATIONS', 'locations');
define('LOCATIONS_UPDATED_SUCCESSFULLY', 'Mekanlar başarıyla güncellendi');
define('LOGGED_IN_SUCCESSFULLY', 'Oturum başarıyla açıldı');
define('LOGGED_OUT_SUCCESSFULLY', 'Oturum başarıyla kapatıldı');
define('MAX_PRICE', 'max_price');
define('MIN_PRICE', 'min_price');
define('MESSAGE', 'message');
define('NAME', 'name');
define('NOT_EQUAL_SIGN', '!=');
define('NO_RESULT_TO_SHOW', 'Gösterilecek sonuç bulunamadı');
define('NO_REPLY', 'no-reply@ozelden.com');
define('NO_SUFFICIENT_BIDS', 'Yeterli teklif hakkınız yok');
define('OVER_INTERNET', 'over_internet');
define('PACKAGE_DISCOUNT', 'package_discount');
define('PACKAGES', 'packages');
define('PARENT_ID', 'parent_id');
define('PASSWORD', 'password');
define('PASSWORD_CONFIRMATION', 'password_confirmation');
define('PASSWORD_VALIDATION_FAILED', 'Şifreleri doğrulama hatası');
define('PASSWORD_SEND_TO_MAIL', 'Şifre email adresinize gönderildi');
define('PASSWORD_UPDATED_SUCCESSFULLY', 'Şifre başarıyla güncellendi, lütfen tekrar giriş yapınız');
define('PAID_SERVICE_ID', 'paid_service_id');
define('PAYMENT_VALIDATION_ERROR', 'Ödeme sırasında bir doğrulama hatası oluştu, lütfen tekrar deneyin');
define('PERMISSION_DENIED', 'Bu işlem için izniniz yok');
define('PICTURE', 'picture');
define('PICTURE_UPLOADED_SUCCESSFULLY', 'Fotoğraf başarıyla yüklendi');
define('PHONE', 'phone');
define('PRICE', 'price');
define('PRICE_AVG', 'price_avg');
define('PRICE_DISTRIBUTION', 'price_distribution');
define('PRICE_PLEASURE', 'price_pleasure');
define('PRICE_WITH_COMMISSION', 'price_with_commission');
define('PROFESSION', 'profession');
define('RANKING_AVG', 'ranking_avg');
define('RANGE', 'range');
define('RECEIVER_ID', 'receiver_id');
define('RECEIVER', 'receiver');
define('RECOMMEND', 'recommend');
define('REFERENCE_CODE', 'reference_code');
define('REGISTER_DATE', 'register_date');
define('REGION', 'region');
define('REGIONS', 'regions');
define('REGIONS_UPDATED_SUCCESSFULLY', 'Bölgeler başarıyla güncellendi');
define('REMEMBER_TOKEN', 'remember_token');
define('SEARCH_TYPE', 'search_type');
define('SENDER_ID', 'sender_id');
define('SENDER', 'sender');
define('SENDER_TYPE', 'sender_type');
define('SEX', 'sex');
define('STATE', 'state');
define('STAR_SIGN', '*');
define('STATUS', 'status');
define('STATUS_CODE', 'status_code');
define('STUDENT', 'student');
define('STUDENTS', 'students');
define('STUDENTS_COUNT', 'students_count');
define('STUDENT_ID', 'student_id');
define('STUDENT_HOME', 'student_home');
define('STUDENT_CREATED_SUCCESSFULLY', 'Öğrenci başarıyla oluşturuldu');
define('STUDENT_DELETED_SUCCESSFULLY', 'Öğrenci başarıyla kaldırıldı');
define('STUDENT_UPDATED_SUCCESSFULLY', 'Öğrenci başarıyla güncellendi');
define('SOMETHING_WRONG_WITH_DB', 'Veri tabanıyla bağlanmada bir sorun oluştu');
define('SOMETHING_WRONG_WITH_EMAIL', 'Email gönderilirken bir sorun oluştu');
define('SUCCESS', 'success');
define('SUITABILITY_TYPE', 'suitability_type');
define('SURNAME', 'surname');
define('THIS_EMAIL_ALREADY_EXIST', 'Bu email sistemde zaten mevcut');
define('THIS_LECTURE_ALREADY_EXISTS', 'Bu ders listede zaten mevcut');
define('TIME', 'time');
define('TOTAL_COUNT', 'total_count');
define('TOTAL_DATA', 'total_data');
define('TOTAL_PAGE', 'total_page');
define('TURKISH_LIRA', 'TRY');
define('TUTOR', 'tutor');
define('TUTORED', 'tutored');
define('TUTORED_ANNOUNCEMENTS', 'tutored_announcements');
define('TUTORED_ID', 'tutored_id');
define('TUTOR_HOME', 'tutor_home');
define('TUTOR_ID', 'tutor_id');
define('TUTOR_LECTURE_ID', 'tutor_lecture_id');
define('TUTOR_LECTURE', 'tutor_lecture');
define('TUTOR_LECTURES', 'tutor_lectures');
define('TUTOR_SUITABILITY', 'tutor_suitability');
define('TUTOR_STATISTICS', 'tutor_statistics');
define('TYPE', 'type');
define('OFFER', 'offer');
define('OFFER_ID', 'offer_id');
define('OFFER_IN', 'offer-in');
define('OFFER_OUT', 'offer-out');
define('OFFER_SENT_SUCCESSFULLY', 'Teklif başarıyla gönderildi');
define('OFFER_STATUS_APPROVED', 1);
define('OFFER_STATUS_EXPIRED', 98);
define('OFFER_STATUS_REJECT', 99);
define('OFFER_STATUS_UPDATED', 2);
define('OFFER_STATUS_WAITING', 0);
define('OFFER_STATUS_UPDATED_SUCCESSFULLY', 'Teklif durumu başarıyla güncellendi');
define('OFFER_TYPE', 'offer_type');
define('OFFERS_COUNT', 'offers_count');
define('ONESIGNAL_DEVICE_ID', 'onesignal_device_id');
define('ORDER', 'order');
define('UPDATED_AT', 'updated_at');
define('USER', 'user');
define('USER_DOES_NOT_EXIST', 'Böyle bir kullanıcı yok');
define('USER_ID', 'user_id');
define('USER_STATE_ACTIVE', 1);
define('VALUE', 'value');
